/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState, useMemo, useEffect } from 'react';
import { 
  Copy, Check, TrendingUp, Shield, BarChart3, 
  Settings, ChevronDown, Rocket, Code2, 
  Zap, RefreshCw, AlertCircle, Sparkles, Info
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { TREND_STRATEGY_PINE, RANGE_STRATEGY_PINE, CRYPTO_BREAKOUT_STRATEGY } from './constants';

interface StrategyParams {
  marketType: 'stocks' | 'forex' | 'crypto';
  strategyStyle: 'trend' | 'range' | 'breakout';
  riskLevel: 'low' | 'medium' | 'high';
  scoreThreshold: number;
  emaFast: number;
  emaSlow: number;
  rsiLen: number;
  volMaLen: number;
  slAtrMult: number;
  tpRrRatio: number;
  useBE: boolean;
  cooldownBars: number;
}

export default function App() {
  const [params, setParams] = useState<StrategyParams>({
    marketType: 'stocks',
    strategyStyle: 'trend',
    riskLevel: 'medium',
    scoreThreshold: 70,
    emaFast: 50,
    emaSlow: 200,
    rsiLen: 14,
    volMaLen: 20,
    slAtrMult: 1.5,
    tpRrRatio: 2.0,
    useBE: true,
    cooldownBars: 5,
  });

  const [isGenerating, setIsGenerating] = useState(false);
  const [showSuccess, setShowSuccess] = useState(false);
  const [copied, setCopied] = useState(false);
  const [activeAccordion, setActiveAccordion] = useState<string | null>('market');

  const generatedPine = useMemo(() => {
    let script = '';
    
    // Select base template
    if (params.strategyStyle === 'range') {
      script = RANGE_STRATEGY_PINE;
    } else if (params.strategyStyle === 'breakout') {
      script = CRYPTO_BREAKOUT_STRATEGY;
    } else {
      script = TREND_STRATEGY_PINE;
    }

    // Apply Replacements
    script = script.replace(/input\.int\(70, "Min Entry Score Threshold"/, `input.int(${params.scoreThreshold}, "Min Entry Score Threshold"`);
    script = script.replace(/input\.int\(50, "Trend EMA \(Fast\)"/, `input.int(${params.emaFast}, "Trend EMA (Fast)"`);
    script = script.replace(/input\.int\(200, "Baseline EMA \(Slow\)"/, `input.int(${params.emaSlow}, "Baseline EMA (Slow)"`);
    script = script.replace(/input\.int\(14, "RSI Length"/, `input.int(${params.rsiLen}, "RSI Length"`);
    script = script.replace(/input\.int\(20, "Volume MA Length"/, `input.int(${params.volMaLen}, "Volume MA Length"`);
    script = script.replace(/input\.float\(1\.5, "ATR Stop Multiplier"/, `input.float(${params.slAtrMult}, "ATR Stop Multiplier"`);
    script = script.replace(/input\.float\(2\.0, "Take Profit \(R:R\)"/, `input.float(${params.tpRrRatio}, "Take Profit (R:R)"`);
    script = script.replace(/input\.bool\(true, "Auto Break-Even \(1:1\)"/, `input.bool(${params.useBE}, "Auto Break-Even (1:1)"`);
    script = script.replace(/input\.int\(5, "Bars Cooldown"/, `input.int(${params.cooldownBars}, "Bars Cooldown"`);
    
    // Add Metadata header
    const header = `// Market: ${params.marketType.toUpperCase()} | Risk: ${params.riskLevel.toUpperCase()} | Generated by PineLab\n`;
    
    // Add Forex Session Filter if applicable
    if (params.marketType === 'forex') {
      const sessionBlock = `
// --- Forex Session Filter ---
use_session = input.bool(true, "NY/London Session Only")
session_time = input.session("0800-1700:23456", "Trading Session")
is_in_session = use_session ? not na(time(timeframe.period, session_time)) : true
entry_allowed := entry_allowed and is_in_session
`;
      // Inject after the initial definition of entry_allowed
      script = script.replace(/(entry_allowed = .+)/, `$1\n\n// --- Forex Session Filter ---\nuse_session = input.bool(true, "NY/London Session Only")\nsession_time = input.session("0800-1700:23456", "Trading Session")\nis_in_session = use_session ? not na(time(timeframe.period, session_time)) : true\nentry_allowed := entry_allowed and is_in_session`);
    }

    return header + script;
  }, [params]);

  // Adjust parameters when market type or risk level changes
  useEffect(() => {
    if (params.riskLevel === 'low') {
      setParams(p => ({ ...p, slAtrMult: 2.5, tpRrRatio: 1.5 }));
    } else if (params.riskLevel === 'high') {
      setParams(p => ({ ...p, slAtrMult: 1.2, tpRrRatio: 3.0 }));
    } else {
      setParams(p => ({ ...p, slAtrMult: 1.8, tpRrRatio: 2.0 }));
    }
  }, [params.riskLevel]);

  // Auto-switch strategy style based on market if user hasn't touched it? 
  // No, let user choose.

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      setShowSuccess(true);
      setTimeout(() => setShowSuccess(false), 3000);
    }, 800);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedPine);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const toggleAccordion = (id: string) => {
    setActiveAccordion(activeAccordion === id ? null : id);
  };

  return (
    <div className="min-h-screen bg-[#0a0c10] text-[#f0f6fc] selection:bg-blue-500/30 font-sans">
      {/* Header */}
      <header className="h-16 border-b border-[#30363d] bg-[#161b22]/50 backdrop-blur-md sticky top-0 z-50 px-6 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center shadow-lg shadow-blue-500/20">
            <Sparkles className="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 className="font-bold text-lg tracking-tight leading-none mb-1">PineLab</h1>
            <p className="text-[10px] text-[#8b949e] uppercase tracking-widest font-semibold">Pro Strategy Lab</p>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <button className="text-xs text-[#8b949e] hover:text-white transition-colors font-medium">Documentation</button>
          <div className="h-4 w-[1px] bg-[#30363d]"></div>
          <button 
            onClick={handleGenerate}
            disabled={isGenerating}
            className="bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white px-5 py-2 rounded-full text-xs font-bold transition-all flex items-center gap-2 active:scale-95"
          >
            {isGenerating ? <RefreshCw className="w-3.5 h-3.5 animate-spin" /> : <Rocket className="w-3.5 h-3.5" />}
            Generate Strategy
          </button>
        </div>
      </header>

      <main className="max-w-[1400px] mx-auto p-8 grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Column: Build Tools */}
        <div className="lg:col-span-4 space-y-6">
          <div className="bg-[#161b22] border border-[#30363d] rounded-2xl overflow-hidden">
            <div className="p-5 border-b border-[#30363d] bg-[#1c2128]">
              <h2 className="text-sm font-bold flex items-center gap-2">
                <Settings className="w-4 h-4 text-blue-400" />
                Strategy Components
              </h2>
            </div>
            
            <div className="divide-y divide-[#30363d]">
              {/* Market Configuration Accordion */}
              <AccordionItem 
                id="market" 
                title="Strategy DNA" 
                icon={<Settings className="w-4 h-4" />}
                active={activeAccordion === 'market'}
                onToggle={() => toggleAccordion('market')}
              >
                <div className="space-y-4 pt-2">
                  <div className="space-y-2">
                    <label className="text-[11px] font-bold text-[#8b949e] uppercase tracking-wider block">Target Market</label>
                    <select 
                      value={params.marketType}
                      onChange={(e: any) => setParams({...params, marketType: e.target.value})}
                      className="w-full bg-[#0d1117] border border-[#30363d] rounded-xl px-4 py-2.5 text-sm focus:border-blue-500/50 outline-none transition-all font-medium appearance-none"
                    >
                      <option value="stocks">Trending Stocks (NVDA, MSFT)</option>
                      <option value="crypto">Crypto Volatility (BTC, ETH)</option>
                      <option value="forex">Forex (EURUSD, GBPUSD)</option>
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label className="text-[11px] font-bold text-[#8b949e] uppercase tracking-wider block">Strategy Style</label>
                    <select 
                      value={params.strategyStyle}
                      onChange={(e: any) => setParams({...params, strategyStyle: e.target.value})}
                      className="w-full bg-[#0d1117] border border-[#30363d] rounded-xl px-4 py-2.5 text-sm focus:border-blue-500/50 outline-none transition-all font-medium appearance-none"
                    >
                      <option value="trend">Trend Following (EMA Based)</option>
                      <option value="range">Mean Reversion (BB/RSI)</option>
                      <option value="breakout">Momentum Breakout</option>
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label className="text-[11px] font-bold text-[#8b949e] uppercase tracking-wider block">Risk Alignment</label>
                    <div className="grid grid-cols-3 gap-2">
                      {['low', 'medium', 'high'].map(r => (
                        <button
                          key={r}
                          onClick={() => setParams({...params, riskLevel: r as any})}
                          className={`py-2 rounded-lg text-[10px] font-bold uppercase tracking-wider transition-all border ${
                            params.riskLevel === r 
                              ? 'bg-blue-600 border-blue-500 text-white shadow-lg shadow-blue-500/20' 
                              : 'bg-[#0d1117] border-[#30363d] text-[#8b949e] hover:border-[#484f58]'
                          }`}
                        >
                          {r}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              </AccordionItem>

              {/* Scoring Configuration Accordion (Trend Only) */}
              {params.strategyStyle === 'trend' && (
                <AccordionItem 
                  id="scoring" 
                  title="Trade Quality Scoring" 
                  icon={<BarChart3 className="w-4 h-4" />}
                  active={activeAccordion === 'scoring'}
                  onToggle={() => toggleAccordion('scoring')}
                >
                  <div className="space-y-4 pt-2">
                    <div className="p-3 bg-indigo-500/5 rounded-xl border border-indigo-500/10 mb-2">
                      <p className="text-[10px] text-indigo-400 font-medium leading-tight">
                        Score = Trend (30) + Momentum (25) + Volume (20) + Vola (15) + Pullback (10).
                      </p>
                    </div>
                    <InputField 
                      label="Min Entry Score (0-100)" 
                      value={params.scoreThreshold} 
                      onChange={(v: number) => setParams({...params, scoreThreshold: v})}
                    />
                    <div className="grid grid-cols-2 gap-4">
                      <InputField 
                        label="Trend EMA (Fast)" 
                        value={params.emaFast} 
                        onChange={(v: number) => setParams({...params, emaFast: v})}
                      />
                      <InputField 
                        label="Baseline EMA (Slow)" 
                        value={params.emaSlow} 
                        onChange={(v: number) => setParams({...params, emaSlow: v})}
                      />
                    </div>
                  </div>
                </AccordionItem>
              )}

              {/* Indicator Settings Accordion */}
              <AccordionItem 
                id="indicators" 
                title={params.strategyStyle === 'range' ? "Mean Reversion Logic" : params.strategyStyle === 'breakout' ? "Breakout Logic" : "Technical Filters"} 
                icon={<TrendingUp className="w-4 h-4" />}
                active={activeAccordion === 'indicators'}
                onToggle={() => toggleAccordion('indicators')}
              >
                <div className="space-y-4 pt-2">
                  {params.strategyStyle === 'trend' && (
                    <div className="grid grid-cols-2 gap-4">
                      <InputField 
                        label="RSI Length" 
                        value={params.rsiLen} 
                        onChange={(v: number) => setParams({...params, rsiLen: v})}
                      />
                      <InputField 
                        label="Volume MA" 
                        value={params.volMaLen} 
                        onChange={(v: number) => setParams({...params, volMaLen: v})}
                      />
                    </div>
                  )}
                  {params.strategyStyle === 'range' && (
                    <>
                      <div className="grid grid-cols-2 gap-4">
                        <InputField label="BB Length" value={20} onChange={() => {}} />
                        <InputField label="BB Multiplier" type="float" value={2.0} onChange={() => {}} />
                      </div>
                      <div className="grid grid-cols-2 gap-4">
                        <InputField label="RSI Length" value={14} onChange={() => {}} />
                        <InputField label="RSI Overbought" value={70} onChange={() => {}} />
                      </div>
                    </>
                  )}
                  {params.strategyStyle === 'breakout' && (
                    <>
                      <InputField label="Breakout Lookback" value={20} onChange={() => {}} />
                      <div className="grid grid-cols-2 gap-4">
                        <InputField label="Volume MA" value={20} onChange={() => {}} />
                        <InputField label="Vol Spike Mult" type="float" value={2.0} onChange={() => {}} />
                      </div>
                    </>
                  )}
                  <p className="text-[9px] text-[#484f58] uppercase font-bold tracking-widest mt-2 px-1">Optimization active</p>
                </div>
              </AccordionItem>

              {/* Risk Management Accordion */}
              <AccordionItem 
                id="risk" 
                title="Adaptive Risk Management" 
                icon={<Shield className="w-4 h-4" />}
                active={activeAccordion === 'risk'}
                onToggle={() => toggleAccordion('risk')}
              >
                <div className="space-y-4 pt-2">
                  <div className="grid grid-cols-2 gap-4">
                    <InputField 
                      label="SL ATR Mult" 
                      type="float" 
                      value={params.slAtrMult} 
                      onChange={(v) => setParams({...params, slAtrMult: v})}
                    />
                    <InputField 
                      label="Target R:R" 
                      type="float" 
                      value={params.tpRrRatio} 
                      onChange={(v) => setParams({...params, tpRrRatio: v})}
                    />
                  </div>
                  <InputField 
                    label="Cooldown Bars" 
                    value={params.cooldownBars} 
                    onChange={(v) => setParams({...params, cooldownBars: v})}
                  />
                  <CheckboxField 
                    label="Auto Break-Even (1:1)" 
                    checked={params.useBE} 
                    onChange={(v) => setParams({...params, useBE: v})} 
                  />
                </div>
              </AccordionItem>
            </div>
          </div>

          <div className="p-4 bg-blue-500/5 border border-blue-500/10 rounded-xl flex gap-3 italic">
            <Info className="w-5 h-5 text-blue-400 shrink-0" />
            <p className="text-[11px] text-[#8b949e] leading-relaxed">
              These settings configure the <span className="text-blue-400 font-medium">Pine Script V5</span> code dynamically. Adjust values to fine-tune your entry filters and risk parameters.
            </p>
          </div>
        </div>

        {/* Right Column: Code Output */}
        <div className="lg:col-span-8 space-y-6">
          <div className="bg-[#161b22] border border-[#30363d] rounded-2xl flex flex-col min-h-[600px] shadow-2xl relative overflow-hidden">
            <div className="p-5 border-b border-[#30363d] bg-[#1c2128] flex items-center justify-between sticky top-0 z-10">
              <div className="flex items-center gap-3">
                <div className="flex gap-1.5 px-2">
                  <div className="w-2.5 h-2.5 rounded-full bg-[#30363d]"></div>
                  <div className="w-2.5 h-2.5 rounded-full bg-[#30363d]"></div>
                  <div className="w-2.5 h-2.5 rounded-full bg-[#30363d]"></div>
                </div>
                <div className="h-4 w-[1px] bg-[#30363d]"></div>
                <div className="flex items-center gap-2">
                  <Code2 className="w-4 h-4 text-green-400" />
                  <span className="text-xs font-mono font-medium text-[#8b949e]">pine_strategy_v1.pine</span>
                </div>
              </div>
              
              <button 
                onClick={handleCopy}
                className={`flex items-center gap-2 px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${
                  copied ? 'bg-green-600/10 text-green-400' : 'bg-[#30363d] hover:bg-[#444c56] text-[#f0f6fc]'
                }`}
              >
                {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? 'Copied' : 'Copy Code'}
              </button>
            </div>

            <div className="flex-1 p-6 font-mono text-[13px] leading-relaxed relative bg-[#0d1117] overflow-auto custom-scrollbar">
              <AnimatePresence mode="wait">
                {isGenerating ? (
                  <motion.div 
                    key="generating"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="absolute inset-0 z-20 flex flex-col items-center justify-center bg-[#0d1117]/80 backdrop-blur-sm"
                  >
                    <RefreshCw className="w-8 h-8 text-blue-500 animate-spin mb-4" />
                    <p className="text-sm font-medium animate-pulse">Compiling Strategy...</p>
                  </motion.div>
                ) : (
                  <motion.div
                    key="code"
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="grid grid-cols-[3rem_1fr] relative"
                  >
                    <div className="text-right pr-4 text-[#484f58] select-none border-r border-[#30363d] mr-4">
                      {generatedPine.split('\n').map((_, i) => (
                        <div key={i}>{i + 1}</div>
                      ))}
                    </div>
                    <div className="text-[#c9d1d9] whitespace-pre">
                      {generatedPine.split('\n').map((line, i) => (
                        <div key={i}>
                          <CodeLine content={line} />
                        </div>
                      ))}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            {/* Success Toast Overlay */}
            <AnimatePresence>
              {showSuccess && (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: 20 }}
                  className="absolute bottom-6 left-1/2 -translate-x-1/2 bg-green-600 text-white px-6 py-3 rounded-full flex items-center gap-3 shadow-xl z-30"
                >
                  <Check className="w-5 h-5" />
                  <span className="font-bold text-sm">Strategy Logic Validated & Generated</span>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>
      </main>
    </div>
  );
}

function AccordionItem({ id, title, icon, active, onToggle, children }: any) {
  return (
    <div className="group">
      <button 
        onClick={onToggle}
        className={`w-full flex items-center justify-between p-5 transition-colors ${active ? 'bg-blue-500/5' : 'hover:bg-[#1c2128]'}`}
      >
        <div className="flex items-center gap-3">
          <div className={`${active ? 'text-blue-400' : 'text-[#8b949e]'} transition-colors`}>{icon}</div>
          <span className={`text-[13px] font-bold ${active ? 'text-[#f0f6fc]' : 'text-[#8b949e]'}`}>{title}</span>
        </div>
        <ChevronDown className={`w-4 h-4 text-[#484f58] transition-transform ${active ? 'rotate-180' : ''}`} />
      </button>
      <AnimatePresence>
        {active && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="overflow-hidden"
          >
            <div className="px-5 pb-5 pt-1">
              {children}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function InputField({ label, value, onChange, type = 'int' }: any) {
  return (
    <div className="space-y-2">
      <label className="text-[11px] font-bold text-[#8b949e] uppercase tracking-wider block">{label}</label>
      <input 
        type="number"
        step={type === 'float' ? '0.1' : '1'}
        value={value}
        onChange={(e) => onChange(type === 'float' ? parseFloat(e.target.value) || 0 : parseInt(e.target.value) || 0)}
        className="w-full bg-[#0d1117] border border-[#30363d] rounded-xl px-4 py-2.5 text-sm focus:border-blue-500/50 focus:ring-4 focus:ring-blue-500/10 outline-none transition-all font-medium"
      />
    </div>
  );
}

function CheckboxField({ label, checked, onChange }: any) {
  return (
    <div 
      onClick={() => onChange(!checked)}
      className="flex items-center justify-between p-3 rounded-xl border border-[#30363d] hover:border-[#484f58] transition-all cursor-pointer group select-none mt-2"
    >
      <span className="text-[12px] font-medium text-[#f0f6fc]">{label}</span>
      <div className={`w-10 h-6 rounded-full transition-all relative ${checked ? 'bg-blue-600 shadow-inner' : 'bg-[#30363d]'}`}>
        <div className={`absolute top-1 bg-white w-4 h-4 rounded-full transition-transform shadow-md ${checked ? 'left-5' : 'left-1'}`} />
      </div>
    </div>
  );
}

function CodeLine({ content }: { content: string }) {
  if (content.trim().startsWith('//')) {
    return <div className="text-[#8b949e] italic">{content}</div>;
  }
  
  // Simple regex highlighting for visual feel
  const highlight = (text: string) => {
    return text.split(/([(),= ]+)/).map((part, pi) => {
      if (['strategy', 'input', 'plot', 'ta.ema', 'ta.rsi', 'ta.macd', 'ta.crossover', 'ta.crossunder'].includes(part)) {
        return <span key={pi} className="text-[#ff7b72]">{part}</span>;
      }
      if (part.includes('"')) {
        return <span key={pi} className="text-[#a5d6ff]">{part}</span>;
      }
      if (/^-?\d+\.?\d*$/.test(part)) {
        return <span key={pi} className="text-[#79c0ff]">{part}</span>;
      }
      if (['true', 'false', 'na'].includes(part)) {
        return <span key={pi} className="text-[#ff7b72] underline decoration-dotted underline-offset-4">{part}</span>;
      }
      return part;
    });
  };

  return <div className="h-5">{highlight(content)}</div>;
}
